/**
 * Generates src/common/bells.js and src/common/mock.js from shared/.
 *
 * The band cannot read shared/*.json at runtime, so the data has to be baked
 * into the bundle. Generating it keeps one source of truth with the server;
 * test/shared-sync.test.js fails if the generated files drift.
 *
 *   node scripts/gen-shared.mjs
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const shared = join(root, '..', 'shared')
const outDir = join(root, 'src', 'common')

const HEADER = '// Generated by scripts/gen-shared.mjs from shared/. Do not edit by hand.\n'

function read(name) {
  return JSON.parse(readFileSync(join(shared, name), 'utf8'))
}

function emit(name, exportName, value) {
  const body = `${HEADER}\nexport default ${JSON.stringify(value, null, 2)}\n`
  mkdirSync(outDir, { recursive: true })
  writeFileSync(join(outDir, name), body, 'utf8')
  return body.length
}

const bells = read('bells.json')
const example = read('example.json')

const bellsSize = emit('bells.js', 'bells', bells)
// Phase 2 runs entirely on this sample until interconnect is wired up.
const mockSize = emit('mock.js', 'mock', example)

console.log(`src/common/bells.js  ${bellsSize} bytes  (${bells.pairs.length} pairs)`)
console.log(
  `src/common/mock.js   ${mockSize} bytes  (${example.days.length} days, ` +
    `${example.days.reduce((n, d) => n + d.l.length, 0)} lessons)`
)
