//! Emits the exact frames the plugin would send, as a fixture for the band app.
//!
//! The two sides of the protocol live in different languages, so the only way
//! to keep them honest is to let the real sender produce the bytes and let the
//! real receiver consume them. band-app/test/cross-protocol.test.js feeds this
//! file through the watch-side state machine.
//!
//!   cargo run -p omsu-sync-core --example emit_frames \
//!       --target x86_64-unknown-linux-gnu

use std::fs;
use std::path::PathBuf;

use omsu_sync_core::protocol::{inspect_payload, plan_send};

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("repository root")
        .to_path_buf();

    let example = fs::read_to_string(root.join("shared/example.json")).expect("shared/example.json");
    let compact: String = {
        let value: serde_json::Value = serde_json::from_str(&example).expect("valid json");
        serde_json::to_string(&value).expect("re-encode")
    };

    let info = inspect_payload(&compact).expect("example payload must be valid");
    let real = plan_send(&compact, &info.h);

    // A payload far past the single-frame ceiling, so the chunked path is
    // exercised too. Real schedules never get this big, but the code must
    // still be correct if one ever does.
    let padded = {
        let mut value: serde_json::Value = serde_json::from_str(&compact).expect("json");
        let filler = "Очень длинное название дисциплины ".repeat(600);
        value["_pad"] = serde_json::Value::String(filler);
        serde_json::to_string(&value).expect("re-encode")
    };
    let padded_hash = info.h.clone();
    let chunked = plan_send(&padded, &padded_hash);
    assert!(!chunked.single, "padded payload should need chunking");

    let fixture = serde_json::json!({
        "note": "Generated by astrobox-plugin/core/examples/emit_frames.rs. Do not edit.",
        "single": {
            "hash": real.hash,
            "payload_bytes": real.payload_bytes,
            "frames": real.frames,
        },
        "chunked": {
            "hash": chunked.hash,
            "payload_bytes": chunked.payload_bytes,
            "payload": padded,
            "frames": chunked.frames,
        }
    });

    let out = root.join("band-app/test/data/plugin-frames.json");
    fs::create_dir_all(out.parent().unwrap()).expect("create fixture dir");
    fs::write(&out, serde_json::to_string_pretty(&fixture).unwrap()).expect("write fixture");

    println!("wrote {}", out.display());
    println!(
        "  single : {} frame(s), {} bytes payload",
        real.frame_count(),
        real.payload_bytes
    );
    println!(
        "  chunked: {} frame(s), {} bytes payload",
        chunked.frame_count(),
        chunked.payload_bytes
    );
}
